-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE dbo.clients
(
    id bigint NOT NULL,
    "UserID" character varying(5) NOT NULL,
    fname character varying(50) NOT NULL,
    lname character varying(50),
    dob date NOT NULL,
    gender character varying(6) NOT NULL,
    email character varying(50) NOT NULL,
    phone_number character varying(13) NOT NULL,
    password_serial_number character varying(9) NOT NULL,
    description text,
    image_path text,
    created_at datetime2,
    updated_at datetime2,
    PRIMARY KEY (id)
);

CREATE TABLE dbo.packages
(
    id bigint NOT NULL,
    package_name text NOT NULL,
    image_path text NOT NULL,
    duration text NOT NULL,
    price real NOT NULL,
    days integer NOT NULL,
    description text,
    created_at datetime2,
    updated_at datetime2,
    PRIMARY KEY (id)
);

CREATE TABLE dbo.memberships
(
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    package_id bigint NOT NULL,
    instructor_id bigint NOT NULL,
    status text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    payment_date datetime2 NOT NULL,
    payment_status text NOT NULL,
    description text,
    created_at datetime2,
    updated_at datetime2,
    PRIMARY KEY (id)
);

CREATE TABLE dbo.instructors
(
    id bigint NOT NULL,
    "InstructorID" character varying(5) NOT NULL,
    fname character varying(50) NOT NULL,
    lname character varying(50) NOT NULL,
    dob date NOT NULL,
    gender character varying(6) NOT NULL,
    salary real NOT NULL,
    email character varying(50) NOT NULL,
    title text NOT NULL,
    description text,
    phone_number character varying(13) NOT NULL,
    image_path text,
    created_at datetime2,
    updated_at datetime2,
    PRIMARY KEY (id)
);

CREATE TABLE dbo.payments
(
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    payment_type character varying(10) NOT NULL,
    description text,
    created_at datetime2,
    updated_at datetime2,
    PRIMARY KEY (id)
);

CREATE TABLE dbo.admins
(
    id bigint NOT NULL,
    "AdminID" character varying(5) NOT NULL,
    fname character varying(50) NOT NULL,
    lname character varying(50) NOT NULL,
    dob date NOT NULL,
    gender character varying(6) NOT NULL,
    email character varying(50) NOT NULL,
    password text NOT NULL,
    phone_number character varying(13) NOT NULL,
    description text,
    image_path text,
    created_at datetime2,
    updated_at datetime2,
    PRIMARY KEY (id)
);

CREATE TABLE dbo.attendance
(
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    session_id bigint NOT NULL,
    description text,
    created_at datetime2,
    updated_at datetime2,
    PRIMARY KEY (id)
);

CREATE TABLE dbo.sessions
(
    id bigint NOT NULL,
    instructor_id bigint NOT NULL,
    membership_id bigint NOT NULL,
    destination_date date NOT NULL,
    is_attended boolean NOT NULL,
    description text,
    created_at datetime2,
    updated_at datetime2,
    PRIMARY KEY (id)
);

ALTER TABLE dbo.memberships
    ADD FOREIGN KEY (client_id)
    REFERENCES dbo.clients (id) 
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE dbo.memberships
    ADD FOREIGN KEY (package_id)
    REFERENCES dbo.packages (id) 
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE dbo.memberships
    ADD FOREIGN KEY (instructor_id)
    REFERENCES dbo.instructors (id) 
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE dbo.payments
    ADD FOREIGN KEY (client_id)
    REFERENCES dbo.clients (id) 
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE dbo.attendance
    ADD FOREIGN KEY (client_id)
    REFERENCES dbo.clients (id) 
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE dbo.attendance
    ADD FOREIGN KEY (session_id)
    REFERENCES dbo.sessions (id) 
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE dbo.sessions
    ADD FOREIGN KEY (instructor_id)
    REFERENCES dbo.instructors (id) 
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE dbo.sessions
    ADD FOREIGN KEY (membership_id)
    REFERENCES dbo.memberships (id) 
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;